# use kubernetes api version v1 to create ConfigMap
apiVersion: v1
# use ConfigMap object
kind: ConfigMap
# set metadata
metadata:
  # set metadata name to data-tier-config
  name: data-tier-config
# set data to be stored
data:
  # set mongo.conf for mongodb configuration to store the data in /data/db
  mongo.conf: |
    storage:
      dbPath: /data/db;
