# use kubernetes api version v1 to create Secret
apiVersion: v1
# use Secret object
kind: Secret
# set metadata
metadata:
  # set metadata name to data-tier-secret
  name: data-tier-secret
  # set metadata namespace to karsajobs
  namespace: karsajobs
# set secret type to Opaque
type: Opaque
# set data to be stored in base64 encoded
data:
  # set MONGO_ROOT_USERNAME to admin
  MONGO_ROOT_USERNAME: YWRtaW4=
  # set MONGO_ROOT_PASSWORD to supersecretpassword
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA==