apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: data-tier
  labels:
    app: karsajobs
    tier: data
spec:
  selector:
    matchLabels:
      app: karsajobs
      tier: data
  serviceName: data-tier
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: karsajobs
        tier: data
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - imagePullPolicy: Always
          name: mongo
          image: mongo:6.0.6
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME_FILE
              value: /etc/mongo-credentials/MONGO_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD_FILE
              value: /etc/mongo-credentials/MONGO_ROOT_PASSWORD
          volumeMounts:
            - mountPath: /data/db
              name: data-tier-persistent-storage
            - mountPath: /config
              name: data-tier-config-map
            - mountPath: /etc/mongo-credentials
              name: data-tier-secret-credentials
      volumes:
        - name: data-tier-persistent-storage
          persistentVolumeClaim:
            claimName: data-tier-pv-claim
        - name: data-tier-config-map
          configMap:
            name: data-tier-config
        - name: data-tier-secret-credentials
          secret:
            secretName: data-tier-secret