apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  selector:
    matchLabels:
      app: mongo
      tier: backend
  serviceName: mongo
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: mongo
        tier: backend
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo:latest
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: /etc/mongo-credentials/MONGO_ROOT_USERNAME
            - name: MONGO_INIT_DB_ROOT_PASSWORD
              value: /etc/mongo-credentials/MONGO_ROOT_PASSWORD
          volumeMounts:
            - mountPath: /data/db
              name: mongo-persistent-storage
            - mountPath: /config
              name: mongo-config-map
            - mountPath: /etc/mongo-credentials
              name: mongo-secret-credentials
      volumes:
        - name: mongo-persistent-storage
          persistentVolumeClaim:
            claimName: mongo-pv-claim
        - name: mongo-config-map
          configMap:
            name: mongo-config
        - name: mongo-secret
          secret:
            secretName: mongo-secret