apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-tier
  labels:
    app: karsajobs
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karsajobs
      tier: backend
  template:
    metadata:
      labels:
        app: karsajobs
        tier: backend
    spec:
      containers:
        - name: karsajobs
          image: ghcr.io/livoir/karsajobs:latest
          ports:
            - containerPort: 8080
          env:
            - name: APP_PORT
              value: "8080"
            - name: MONGO_HOST
              value: "data-tier"
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  key: MONGO_ROOT_USERNAME
                  name: data-tier-secret
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  key: MONGO_ROOT_PASSWORD
                  name: data-tier-secret