apiVersion: v1
kind: Service
metadata:
  name: backend-tier
  labels:
    app: karsajobs
    tier: backend
spec:
  type: NodePort
  ports:
    - nodePort: 30001
      port: 8080
  selector:
    tier: backend

