apiVersion: v1
kind: Service
metadata:
  name: backend-tier
  labels:
    app: karsajobs
    tier: backend
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30001
  selector:
    tier: backend

